# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "ğŸ‡«ğŸ‡· Polynesie FranÃ§aise ğŸ‡µğŸ‡«"
description:	       "DÃ©couvrez notre prochain voyage dans la nature vierge de la polynÃ©sie franÃ§aise"
author:              "Luca & Margherita"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
